version: '3.7'
services: 
  backend: 
    build: 
      context: .
    ports: 
      - 3000:3000
    env_file:
      - .env
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - db
    
  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: 'splitpay'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'IaaBoy234'
      MYSQL_ROOT_PASSWORD: 'Abracadabra@1234'
      BASE_URL: ''
    volumes: 
      - .dbdata:/var/lib/mysql
    env_file:
      - .env
    ports: 
      - 3316:3306

